### ISSUE TITLE
Copy Link does not work

### ISSUE THREAD

**Issue by sreu94** [urania-dev/snapp#11]
Hi, 
am I wrong or does the "Copy" Action under Dashboard does not work?

**Comment by urania-dev** [comment]
ok this is more troublesome. let's start with "it works on my pc", do you receive any weird log in console.log or docker?
also are you linking the db to a volume or using it volatile? (as in docker run, i'm not sure about persistance throu different docker restarts)

**Comment by urania-dev** [comment]
also do you receive the toast?

**Comment by sreu94** [comment]
Initially I ran it without any volumes or bindings.

Logs look like normal I guess:
`Container started
11.01.2024
13:11:17
🖥️  Starting handle server side
11.01.2024
13:11:20
npm notice 
11.01.2024
13:11:20
npm notice New minor version of npm available! 10.2.3 -> 10.3.0
11.01.2024
13:11:20
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.3.0>
11.01.2024
13:11:20
npm notice Run `npm install -g npm@10.3.0` to update!
11.01.2024
13:11:20
npm notice 
11.01.2024
13:11:20
Prisma schema loaded from prisma/schema.prisma
11.01.2024
13:11:20
Datasource "db": SQLite database "db.sqlite" at "file:./db.sqlite"
11.01.2024
13:11:20
11.01.2024
13:11:20
The database is already in sync with the Prisma schema.
11.01.2024
13:11:20
11.01.2024
13:11:20
Running generate... (Use --skip-generate to skip the generators)
11.01.2024
13:11:20
AGRunning generate... - Prisma Client
11.01.2024
13:11:20
AG✔ Generated Prisma Client (v5.6.0) to ./node_modules/@prisma/client in 293ms
11.01.2024
13:11:20
11.01.2024
13:11:20
11.01.2024
13:11:20
Database is up to date.
11.01.2024
13:11:20
🕐 Setting up Scheduled Jobs
11.01.2024
13:11:20
--- 🧹 Cleaning (0) Scheduled Jobs already set.
11.01.2024
13:11:20
--- ✔️  (1) Jobs Scheduled
11.01.2024
13:11:20
Listening on 0.0.0.0:3000`

I just tried to recreate it with a volume, but cannot copy the link as well.



> also do you receive the toast?

What do you mean by toast?

**Comment by urania-dev** [comment]
the notification of "url has been copied" in the bottom right corner 
![immagine](https://github.com/urania-dev/snapp/assets/153094889/f7b20e7e-aab4-42cc-a3a6-fb233ee65fb3)

**Comment by urania-dev** [comment]
also, try new version

**Comment by sreu94** [comment]
> the notification of "url has been copied" in the bottom right corner 


No, there is no notification.

I will try the new version

**Comment by urania-dev** [comment]
let's try a different approach, what system are you using? where is installed the app? which browser and os are you tyring to use it with? :)

**Comment by sreu94** [comment]
System:
Ubuntu Ubuntu 20.04.6 LTS focal with kernel 5.4.0-164-generic
Docker 24.0.5 and docker-compose version 1.29.2, build 5becea4c
The compose file is under /opt/stacks the volume under /var/lib/docker
Browser:
Edge Version 120.0.2210.121

In your demo version copying works, just not on my container.

I just tried pulling the latest version, but without any success and now I am stuck at downloading the image.
What was the old version tag?

**Comment by urania-dev** [comment]
image won't download?

**Comment by urania-dev** [comment]
yeah, it seems related to the db, can i ask you to provide compose?

**Comment by sreu94** [comment]
`version: "3.3"
services:
  snapp:
    container_name: snapp
    hostname: snapp
    restart: unless-stopped
    ports:
      - 8003:3000
    environment:
      - ORIGIN=http://my.domain:8003
      - PUBLIC_URL=http://my.domain:8003
      - NODE_ENV=development
      - ENABLE_MULTIUSER=true
    image: uraniadev/snapp:0.5
    volumes:
      - snapp-data:/app/prisma
    networks:
      - npm
networks:
  npm:
    external: true
volumes:
  snapp-data:
    external: true
    #https://noted.lol/snapp/
    #https://hub.docker.com/r/uraniadev/snapp
`

**Comment by urania-dev** [comment]
ok, as i tought, you linked as a volume the entire directory, i suspect that it will try to look for the scheme in the same folder. 
just touch a db.sqlite file in the folder of your choice and point at it.

- home/user/snapp/db.sqlite:/app/prisma/db.sqlite

check if it solve the problem :)

**Comment by sreu94** [comment]
Ok, the container is up and running again.
Copying the link still does not work unfortunately

**Comment by urania-dev** [comment]
Sad to ear that. 

I'm currently working on version 0.6.2 and 0.6.3, if you are willingly we can plan to check the setup togethere maybe on discord one of this days. 

(are you in GMT+1 timezone, right?)

**Comment by sreu94** [comment]
Yeah we can do that

**Comment by urania-dev** [comment]
I don't know if you had the chance of reading issue pinned in top, after thinking about your issue and the requested features, i decided to remove tabler as i first started just to try It out, it Is good, but maybe something i can control better can improve user experience. 

I ask you to kindly wait for next release, should not take that long and will aim to solve this :)

**Comment by sreu94** [comment]
ok, no problem.
I will try when it is available

**Comment by urania-dev** [comment]
thank you for your understanding. i will close this issue, but feel free to reopen it whenever you deem it necessary :)

**Comment by urania-dev** [comment]
I now know why. Implementing new version i noticed that the documentation changed through the years and clipboard is only available through HTTPS, so maybe that's the reason why your instance doesn't want to copy urls.

try secure your localhost / my.domain with https 

or list it in your browser settings, if allowed

[https://bobbyhadz.com/blog/navigator-clipboard-is-undefined-in-javascript](Here an article talking about it)
