### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'global:appname')

### ISSUE THREAD

**Issue by mariushosting** [urania-dev/snapp#19]
Unable to start the new version 0.7

Always get the following error:

TypeError: Cannot read properties of undefined (reading 'global:appname')

Full log:

Listening on 0.0.0.0:3000
You have marked a string field as sortable but RediSearch doesn't support the SORTABLE argument on a TAG for JSON. Ignored.
TypeError: Cannot read properties of undefined (reading 'global:appname')
    at translate (file:///app/build/server/chunks/Icon-yXj8VcnK.js:26:26)
    at file:///app/build/server/chunks/Icon-yXj8VcnK.js:15:49
    at file:///app/build/server/chunks/_layout.svelte-4GB59oPk.js:820:101
    at Object.$$render (file:///app/build/server/chunks/ssr-9Hmc4DKT.js:255:18)
    at Object.default (file:///app/build/server/chunks/index-oLv0bhRz.js:71:119)
    at file:///app/build/server/chunks/layout.svelte-zo3rgdi6.js:4:42
    at Object.$$render (file:///app/build/server/chunks/ssr-9Hmc4DKT.js:255:18)
    at file:///app/build/server/chunks/index-oLv0bhRz.js:60:121
    at $$render (file:///app/build/server/chunks/ssr-9Hmc4DKT.js:255:18)
    at Object.render (file:///app/build/server/chunks/ssr-9Hmc4DKT.js:263:20)

**Comment by urania-dev** [comment]
Seems like it is missing link to translation. 
I'll look into it ASAP. 

As a workaround you can find it.json and en.json in GitHub rep. 

You can link them with docker-compose with edit:


```yml
 volumes:
  - path/to/local/folder:/app/translations
``` 

It should find them.

**Comment by urania-dev** [comment]
Also which compose you are using?

**Comment by mariushosting** [comment]
> Also which compose you are using?

version: "3.9"
services:
  snapp:
    container_name: Snapp
    image: uraniadev/snapp:0.7
    mem_limit: 4g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:false
    restart: on-failure:5
    ports:
      - 6421:3000
    depends_on: 
     redis: 
      condition: service_healthy
    volumes:
      - /volume1/docker/snapp/translations:/app/translations:rw
    environment:
      ORIGIN: https://snapp.mariushosting.synology.me
      PUBLIC_URL: https://snapp.mariushosting.synology.me
      ADMIN_USERNAME: marius
      ADMIN_EMAIL: supergate84@gmail.com
      ADMIN_PASSWORD: mariushosting
      NODE_ENV: production
      ENABLE_MULTIUSER: true #or false if you want to restrict user access
      TIMEZONE: Europe/Bucharest
      SMTP_HOST: smtp.gmail.com
      SMTP_USER: supergate84@gmail.com
      SMTP_PASSWORD: mypsw
      SMTP_FROM: supergate84@gmail.com
      DB_HOST: redis
      DB_PORT: 6379
      AUTH_SECRET: v6M37byB5LwYHCPZyCJzDGNUSsHY4grj
      
  redis:
    image: redis/redis-stack:latest
    container_name: Snapp-REDIS
    volumes:
      - /volume1/docker/snapp/redis:/data:rw
    environment:
      REDIS_ARGS: '--save 60 1 --appendonly yes'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    restart: on-failure:5``

**Comment by urania-dev** [comment]
i would put ro for the translation folder. where the file in the folder or the folder was empty?
try to detach the folder if empty, and should have them included in docker image, you can link it to add more on to try edit them, but it is not mandatory to be accessed

**Comment by mariushosting** [comment]
> i would put ro for the translation folder. were the file in the folder or the folder was empty? try to detach the folder if empty, and should have them included in docker image, you can link it to add more or to try edit them, but it is not mandatory to be accessed

Nothing change with :ro I tried different tests.

**Comment by mariushosting** [comment]
completely removing/detach that line fixed the issue.

```
volumes:
      - /volume1/docker/snapp/translations:/app/translations:rw
```

**Comment by urania-dev** [comment]
i will put not mandatory to have a json, so empty placeholder label will render instead of crashing the app, thou allowing to better identify the problem (also i will comment out the line in readme)

**Comment by urania-dev** [comment]
Also. Thank you for using Snapp, Sorry for the short answers, I tried to get back to you before entering work  😅
