### ISSUE TITLE
SNAPP // v: 0.7.alpha

### ISSUE THREAD

**Issue by mariushosting** [urania-dev/snapp#20]
In the app version 0.7 is marked as alpha.

In the changelog it's marked at 0.7 release

So this version it's version 0.7 or version 0.7.alpha?

**Comment by mariushosting** [comment]
![alpha](https://github.com/urania-dev/snapp/assets/37554361/26cfeba5-2e21-4119-be55-34cb18505dbf)

**Comment by urania-dev** [comment]
0.7 i forgot to update the label

**Comment by mariushosting** [comment]
> 0.7 i forgot to update the label

Thank You! and we can now use the tag :latest for docker?

**Comment by urania-dev** [comment]
Yes. It is the same as 0.7 already

ENV SNAPP_VERSION=0.7.alpha is the culprit. I'll rebuild to 0.7.1 with previous fix and correttiing.env in docketfile as soon as i can

**Comment by mariushosting** [comment]
> Yes. It is the same as 0.7 already
> 
> ENV SNAPP_VERSION=0.7.alpha is the culprit. I'll rebuild to 0.7.1 with previous fix and correttiing.env in docketfile as soon as i can

Perfect Thank you!

**Comment by urania-dev** [comment]
fixed in 0.7.1 /latest, already online :)

**Comment by mariushosting** [comment]
> fixed in 0.7.1 /latest, already online :)

Yeah!!!
