### ISSUE TITLE
Overlaid text issue

### ISSUE THREAD

**Issue by mariushosting** [urania-dev/snapp#21]
![text over](https://github.com/urania-dev/snapp/assets/37554361/0f3c3f26-41ef-4d30-a872-96d83b6653e3)

**Comment by urania-dev** [comment]
to my defense the shortcode was suppose to be short, i didn't tought about long origin, i admit it. 
fixed with 0.7.1 break-all on those long link :)

**Comment by mariushosting** [comment]
> to my defense the shortcode was suppose to be short, i didn't tought about long origin, i admit it. fixed with 0.7.1 break-all on those long link :)

Thank you for taking care of this!

**Comment by urania-dev** [comment]
by the way. i'm just curious did you managed to transfer your url from previous db or you restarted from emtpy state?

**Comment by mariushosting** [comment]
> by the way. i'm just curious did you managed to transfer your url from previous db or you restarted from emtpy state?

Installed a fresh new instance! - https://mariushosting.com/how-to-install-snapp-on-your-synology-nas/ :-)
