### ISSUE TITLE
Admin panel setting to allow http

### ISSUE THREAD

**Issue by Robby3St** [urania-dev/snapp#23]
Hello, I really like your url shortener! When I tried to make a shortlink for a quiz page in my course at university, it rejected accepting the url to the quiz link, which is another url shortener but only accepting http. Since I don’t can change the page I link to to https, it would be nice to have an option to allow to link to those pages. Would this be possible? Thanks!

**Comment by urania-dev** [comment]
i just did a test and it actually works via http:// only, so i assume that your issue is to redirect the url to a non http:// so snapp.li/redirection => http://redirection.site

right?

**Comment by urania-dev** [comment]
And it's live. you can test it downloading the latest (0.7.2) version
