### ISSUE TITLE
Allow unsecure HTTP on Edit Snapp

### ISSUE THREAD

**Issue by Schnurp** [urania-dev/snapp#26]
Hi,
I can create Snapps with HTTP (Allow Unsecure HTTP=enabled). 

But if I want to edit this HTTP Snapp I can´t save this, because the error "The Snapp Original URL is not valid secure https URL." shows up. 

Maybe you can fix that?

**Comment by urania-dev** [comment]
Yes i missed the check on edit. I Will. ;)

**Comment by Schnurp** [comment]
Thank you very much for yout quick reply and help.

**Comment by urania-dev** [comment]
should be fixed in 0.7.3 :)
