### ISSUE TITLE
Unable to create new snapp using the API.

### ISSUE THREAD

**Issue by fergalmoran** [urania-dev/snapp#29]
I'm trying to use the API to submit a new snapp but I'm getting the following error? 

![image](https://github.com/user-attachments/assets/059871d6-c76d-4a76-bb72-74ef4fd9f8fc)

My PUBLIC_URL & ORIGIN match the URL I'm hosting this on.

Any advise would be most welcome?

**Comment by urania-dev** [comment]
I'll look into into it. Try node_env=development

Not a solution, but a work around atm. 

I'm trying to work on a more robust release, that will probably be a major breaking change update, BUT should work better and be more maintainable. As soon as I get the time. 🥲

**Comment by fergalmoran** [comment]
node_env didn't work I'm afraid.
Don't stress yourself out, great product and I'm getting tons of use out of it. Thanks so much!

**Comment by urania-dev** [comment]
ahahah thank you for your support.

To be honest i'm trying my best with the new version, i think my error has been keeping the api in formdata, which trigger the form and formactions security check for svelte, i didn't thought about that. in the new version i'm trying to keep only json payloads for the api, and it seems to be working, by far.

I remember it working also in the previous version, so i think i miss some how to migrate something among version.

Thank you for the time it took you to allow me know the bug, i'll try to improve in the next version that i hope to delive before the end of august (side project indeed it is part of my holiday from the office)

Can I ask you some insight on how you use the app? :)

**Comment by fergalmoran** [comment]
Great stuff, looking forward to the new version.

I'm hoping to use it for shorturls for an app that I'm working on. I started writing a little CLI and that's how I noticed the POST wasn't working.

**Comment by urania-dev** [comment]
should be fied in new snapp:0.8

**Comment by fergalmoran** [comment]
Unfortunately the CORS error is still here with the new version (0.8.1) - am I crafting the POST correctly? GET requests still work fine and return my list of snapps.

![image](https://github.com/user-attachments/assets/ca49d774-5b4b-4cd8-8ae0-12c349a6cd2a)

**Comment by urania-dev** [comment]
yes, this time i have an answer, try with application/json header content type, as it changed with 0.8 to prevent the svelte security concern about form submission (previously used), swagger is updated, try to launch the api call from there, as it should give you back also the configuration of request!

**Comment by fergalmoran** [comment]
Excellent - works great!! I hate sending form data to APIs anyway so this is perfect!
Thanks so much for all your work getting this working!!
