### ISSUE TITLE
Pasting an URL to 'Original URL' leads to string duplication

### ISSUE THREAD

**Issue by schuesslerma** [urania-dev/snapp#36]
## Feature
Create / Edit a snapp

### Environment
Docker container with image uraniadev/snapp:0.8.1
Utilizing the default database configuration (sqlite)

## Steps to reproduce
1. Log in with a valid user
2. Navigate to 'DASHBOARD'
3. Click '+ Shorten an URL'
4. Paste the valid URL **https://example.com** to 'Original URL' via:
    - keyboard shortcut: Ctrl + V
    - browser context menu: Right click -> Paste

## Expected Result
The value of 'Original URL' is **https://example.com**

### Actual Result
The value of 'Original URL' is **https://example.comhttps://example.com**

## Side note
Pasting the URL via the clipboard button in the input field works as expected

### Assumption
Pasting with keyboard or context menu additionally triggers the clipboard function,
which leads to a string duplication.

**Comment by urania-dev** [comment]
i can fix this and add it to 0.8.2

**Comment by urania-dev** [comment]
should be fixed 👍
