### ISSUE TITLE
import from Shlink

### ISSUE THREAD

**Issue by cirrusflyer** [urania-dev/snapp#38]
Really like the project.  Any way to import from Shlink?

**Comment by urania-dev** [comment]
I have to be honest, never used Shlink, does it provide a csv like file?

**Comment by cirrusflyer** [comment]
Yes, it does.  Here's a sample export:

"createdAt","domain","shortCode","shortUrl","longUrl","title","tags","visits"
"2024-08-15T15:03:56-04:00","myshortdomain.com","9r2TW","https://myshortdomain.com/9r2TW","https://www.realdomain.com/text/text","customtitle","testtag",61

**Comment by urania-dev** [comment]
So...

I gave it a look, without releasing a new version you can patch up a bash script like this, and it should recreate the structure original-url => shortcode

it doesn't migrate uses tho. and i found a bug that doens't migrate the creation either.

if you are ok with just don't have to insert manually all the link you can give it a shot:

```bash
#!/bin/bash

# Define absolute paths for input and output files
input_file="shlink.csv"
output_file="snapp.csv"

# Define the output CSV header
echo "id,created,original_url,has_secret,shortcode,used" > "$output_file"

# Notify the start of processing
echo "Starting CSV conversion..." >&2

# Check if input file exists
if [[ ! -f "$input_file" ]]; then
  echo "Error: Input file $input_file not found." >&2
  exit 1
fi

# Check if output file is writable
if [[ ! -w "$(dirname "$output_file")" ]]; then
  echo "Error: Output directory $(dirname "$output_file") is not writable." >&2
  exit 1
fi

# Process each line in the input CSV (skipping the header)
tail -n +2 "$input_file" | \
  awk -F ',' '{ 
    # Extract relevant fields
    created = $1
    shortcode = $3
    original_url = $5
    visits = $8  # Adjust the field number for visits if needed

    # Generate a unique UUID for the ID
    id = "UUID_PLACEHOLDER"

    # Remove leading and trailing quotes from fields
    gsub(/^"|"$/, "", created)
    gsub(/^"|"$/, "", shortcode)
    gsub(/^"|"$/, "", original_url)

    # Print in CSV format
    printf("\"%s\",\"%s\",\"%s\",\"false\",\"%s\",\"%s\"\n", id, created, original_url, shortcode, visits)
  }' >> "$output_file"

# Notify the end of processing
echo "CSV conversion completed." >&2
```

**Comment by urania-dev** [comment]
also another limittion: look like shlink offer the possibility to change the base url to redirect the user through, while snapp it has its fixed unique base_url

**Comment by cirrusflyer** [comment]
This mostly worked great.  Had some issues with misformatted data, but that's in my file.  I did want to know is there a way to delete all the URLs in Snapp?  So I can start over in testing.

**Comment by cirrusflyer** [comment]
Also, we have some "," (commas) in some URLs.  That obviously breaks the conversion/import process.  And some "|".  Any way to escape these?  Sorry - I'm not a script writer, but I can try.

**Comment by urania-dev** [comment]
So a good way would be having some update in my app, and a semi complete use case of shlink import with said characteristic.

 I think is more than possible to create a little stand alone utility like bash script i shared.

Atm you can delete all the urls one by one, with a cli script, accessing the db from outside. I think i forgot the delete all command or the delete selected from the way you are putting It. 🧐
