### ISSUE TITLE
[FEAT] Change the default page to dashboard when the user is logged in

### ISSUE THREAD

**Issue by AspireOne** [urania-dev/snapp#40]
When the user is not logged in, it makes sense to show the introductory page. However, when an user already is logged in, the dashboard should be shown as the first page. Otherwise it's always unnecesarrily one more click. I would personally REPLACE the introductory page with the dashboard when logged in, and kept it at the root domain (/).

**Comment by urania-dev** [comment]
That is more or less the same result as disabling the homepage 🤔

**Comment by AspireOne** [comment]
And where do I do that?

Dne čt 29. 8. 2024 2:55 odp. uživatel archraziel88 ***@***.***>
napsal:

**Comment by urania-dev** [comment]
In setting > disable homepage![Screenshot_20240829-193335.png](https://github.com/user-attachments/assets/c710de7c-c649-4df6-a586-89606e5e25fa)
