### ISSUE TITLE
Swagger link fixed to snap.li

### ISSUE THREAD

**Issue by gmag11** [urania-dev/snapp#42]
When opening swagger playground in server I cannot use "Try out" function because it sends all requests to snap.li instead of the current host
![image](https://github.com/user-attachments/assets/892e32de-59b8-4c72-963f-cee405997d22)

**Comment by urania-dev** [comment]
would you please download 0.8.5 and confirm this is gone? :)

**Comment by gmag11** [comment]
Yes, solved. Thanks
