### ISSUE TITLE
Swagger link template not filled out

### ISSUE THREAD

**Issue by gmag11** [urania-dev/snapp#43]
Swagger link in Home page does not point to `https://<host>/docs` but `https://<host>/{url}`. Meanwhile using /docs works fine
![image](https://github.com/user-attachments/assets/c26452d3-5075-4b3f-b56b-c329cfb9da49)

**Comment by urania-dev** [comment]
Im at work, i'll be back to you ASAP, but they looks like easy fixable happy accidents (🥲), i should be able to fix them by this afternoon (timez-eur)

**Comment by urania-dev** [comment]
would you please download 0.8.5 and confirm this is gone? :)

**Comment by gmag11** [comment]
Solved. Thanks!
