### ISSUE TITLE
The password provided is not sufficiently secure. Please try again.

### ISSUE THREAD

**Issue by zarevskaya** [urania-dev/snapp#47]
Hello,

I was testing the password reset by email. 

I tested quite a few possibilities with the instructions provided by Snapp.

First try:
$%vO8r0S9GV84Kr&8gVEVEK#73$MIzu&BpF*7xk1  

Second try:
#by%U$!8w6$w8ApmF2i&

And the last try:
cPy%7F^0KKc*rRCe$4n%%aZ@53qG07M&Kxe3OEkibeAJAb

Can you confirm this is a bug or am I the bug? :)

**Comment by urania-dev** [comment]
To be completely honest, I should output the symbols included in the regex, as there appears to be a conflict with missing symbols in the 'allowed' set. In your case, the first and second passwords contain #, and the third contains ^, neither of which are permitted by the current regex.
i'm trying to formulate a better regex.

**Comment by zarevskaya** [comment]
Very weird, I have the same issue with all other tests. Without #, ^. 

I realize that none of the passwords work.

**Comment by urania-dev** [comment]
i think i found a better regex on regex101, it seems to comply with your password and basically the same requirements:
^(?=.*\d)(?=.*[A-Z])(?=.*[a-z])(?=.*[^\w\d])([^\s]){8,}$

https://regex101.com/

let me build 0.8.6.3 😆

**Comment by zarevskaya** [comment]
At your ease :+1:  Thanks!

**Comment by urania-dev** [comment]
yeah, no i mean that it requires 20 minutes, i just launched, and then if you will to try it i would really appreciate.

Also thank you for the massive debugging you took on your shoulder, this kind of feedback helps a lot to improve the app :)

**Comment by urania-dev** [comment]
Thank you for your interest in my application: looking forward to hearing your feedback!

i'll also take a look at the blog while waiting the build to complete. 💯

**Comment by urania-dev** [comment]
Version 0.8.6.3 should be live, and in the meantime, I discovered through your blog that my Proxmox had about 7 unused kernels left on the drive.

**Comment by zarevskaya** [comment]
Let's go to try the new update :fire: 

`I discovered through your blog that my Proxmox had about 7 unused kernels`

What an invasion! ;)

**Comment by urania-dev** [comment]
It was high time for a thorough cleaning. I'm kind of an enthusiast and consider this a hobby, don't judge me. 😆

**Comment by zarevskaya** [comment]
I am no one to judge you, I am in a bad position. GORGEOUS! I can put whatever password I want.

I am finishing my article as complete as possible to detail all your work. The article will be released at midnight tonight.
Great, that was the last detail that gave me trouble explaining the password reset by email.

1009 words at the moment. I will now complete the tutorial. Thank you for your responsiveness! Moreover, it is specified in the article that it was nice to exchange with an attentive dev.

**Comment by urania-dev** [comment]
Thank you so much for your kind words! I'm glad I could help and that everything was clarified. I appreciate the recognition and enjoyed our exchanges as well. Looking forward to reading the article! 🚀

**Comment by zarevskaya** [comment]
Tonight, midnight. Friendships from Belgium!
Now I find your application perfectly usable! Let's goooOooO!

See you soon :)

**Comment by zarevskaya** [comment]
Sorry I'm two minutes late. :smile: 

https://belginux.com/installer-snapp-avec-docker/

If you have a suggestion or comment, I'm all ears.
