### ISSUE TITLE
Add new language

### ISSUE THREAD

**Issue by xja** [urania-dev/snapp#48]
How should I add a new language to the project? I put the translated file under `src/lib/i18n/locales`, and added an entry in `src/lib/i18n/index.ts`, after building using docker build, there is no this new language option showing in the settings page.

[087407f0082e7171e1ac6e12247d027f50d97532](https://github.com/xja/snapp/commit/087407f0082e7171e1ac6e12247d027f50d97532)

**Comment by xja** [comment]
Sorry, I forgot to change the remote url before building. The new language can be selected and applied in settings page now. But there are two problems related still:
1. It shows "Cn" instead of "Simplified Chinese" in the language drop down list
2. All the drop down list boxes are editable on my Android Firefox, making it annoying while trying to select an item because the keyboard would appear

**Comment by urania-dev** [comment]
Languages were translate automatically from the I18N short id, for chinese should work zh if im not wrong. 


Also typing can be deactivated, and since there are not that many languages I could actually disable it there.

**Comment by urania-dev** [comment]
I took the liberty of taking your translation and add it to the next version i'm building. it also fixes the combo-box on mobile, deactivating the input field in order to better manage the choose :)

**Comment by xja** [comment]
OK. Just to let you know, the translation was done using the free Perplexity.ai. I checked it over and fixed any mistakes, but can't guarantee the translations are 100% perfect or ideal.

**Comment by urania-dev** [comment]
Well, for sure is better of what i could ever do. :)
Thank you!
