### ISSUE TITLE
[BUG] I can't short a long link

### ISSUE THREAD

**Issue by mariushosting** [urania-dev/snapp#5]
Unable to short this simple link below: 

https://global.download.synology.com/download/Document/Hardware/HIG/DiskStation/21-year/DS1621xs+/enu/Syno_HIG_DS1621xs_Plus_enu.pdf?_gl=1*1k0gfrs*_ga*MTI0MTE2ODY0LjE2MTIwNTIwNDM.*_ga_9Q8XT3X20D*MTYxMjE4MzcwNC42LjEuMTYxMjE4Mzg0Mi42MA..&_ga=2.140975418.985886723.1612052043-124116864.1612052043

No issue with other URL shortner.

**Comment by urania-dev** [comment]
So, this is due to the https: checker, i suppose there are multiple dots around your link, and that confuse it, i'll try to check and fix this :)

**Comment by urania-dev** [comment]
should be live and able to get that link! 👍

**Comment by mariushosting** [comment]
> should be live and able to get that link! 👍

Thank you!

**Comment by urania-dev** [comment]
closing the issue! :)
