### ISSUE TITLE
Deleting a URL

### ISSUE THREAD

**Issue by acseven** [urania-dev/snapp#52]
Hi!

Record deletion works only using the delete selected button on the top. Inline trash bin icon doesn't work (popup appears but it doesn't do anything). 

<img width="872" alt="image" src="https://github.com/user-attachments/assets/09e896d8-2528-4998-be60-396c89c97c64">

**Comment by urania-dev** [comment]
yeah it look like i forgot to complete the flow. i kind of left it there, at the confirmation check. my bad.

it is now complete 🙏 

uploading 0.8.6.6
