### ISSUE TITLE
Unexpected SQLite Database in Docker Image 

### ISSUE THREAD

**Issue by IvanLi-CN** [urania-dev/snapp#53]
I deployed snapp using Docker (docker.io/uraniadev/snapp: 0.8.6.6) and found an unexpected `db.sqlite` file.

I suspect a `db.sqlite` from a specific environment might have been accidentally copied into the Docker image during the build process.

This is preventing me from initializing my admin account correctly.

Could you please check this? It may also include some classified information.

<img width="1245" alt="image" src="https://github.com/user-attachments/assets/79c5b6b3-607e-4891-8e2b-9140a9af94d8">

After I manually delete this file and restart the container, I can continue.

**Comment by urania-dev** [comment]
you're absolutely right, i forgot to update entrypoint.sh to delete the local dev db. i'm rebuilding 0.8.6.7, it should fix the bug

**Comment by urania-dev** [comment]
try now

**Comment by IvanLi-CN** [comment]
Perfect, I just tried it in a clean environment with the latest mirror and it works great. Thanks for your efforts.
