### ISSUE TITLE
It seems the 'notes' field is missing when importing from CSV

### ISSUE THREAD

**Issue by IvanLi-CN** [urania-dev/snapp#54]
I'm using docker.io/uraniadev/snapp:0.8.6.6. After testing the export and import functions, I noticed that while the CSV file includes the 'notes' field with data during export, this information is lost when importing back into the system.

The issue appears to be in this section of the code:
https://github.com/urania-dev/snapp/blob/ed21ad414443a5218f258ad23bd6d4492938ebe1/src/routes/settings/import/%2Bpage.svelte#L49-L57

Any assistance in resolving this would be greatly appreciated. Thank you!

**Comment by urania-dev** [comment]
i'll add this fix to the queue :)

**Comment by urania-dev** [comment]
try now

**Comment by IvanLi-CN** [comment]
It's working great now! Thank you for your dedication and quick response.

**Comment by urania-dev** [comment]
thank you for taking time to signaling all the bugs :)
