### ISSUE TITLE
[Feature request] Geo Locking

### ISSUE THREAD

**Issue by animencoding** [urania-dev/snapp#62]
redirect users to different locations based on their geo location

**Comment by urania-dev** [comment]
Hello,
what do you mean? can you articulate futher?

**Comment by animencoding** [comment]
Yes, thank you for replying.

this feature will allows for geo-based redirection. Specifically, I want to be able to redirect users to different URLs based on their geographical location.

For example, let's say I have the following short link:
https://mybrand.link/83cd

I want the system to detect the user's country and redirect them accordingly:

    If a user is from France, they should be redirected to website.fr/content.
    If a user is from Spain, they should be redirected to mybrand.es/content.

This feature would enhance user experience by directing users to content that is more relevant to their location.

Here is more info on the feature on a competitor website https://dub.co/help/article/geo-targeting

**Comment by urania-dev** [comment]
this would require a severe rework of most of the app as it involves url creation, edit and fruition. 

it would require (taking inspiration from their API) edit the structure to host different original url based on ip reverse looking, that then would evolve in rewriting most of the app, that is reaching a "stable" point finally, 

i'm not really sure about this.

**Comment by animencoding** [comment]
yeah that's true, for now i can just redirect to my own app and do that 


thanks for the awesome project btw !

**Comment by urania-dev** [comment]
Thank you, sorry to let you down on this one, maybe in future as it happened with the oidc :)
