### ISSUE TITLE
Tags with no paths when feature is on

### ISSUE THREAD

**Issue by LeaveitT0uchless** [urania-dev/snapp#63]
Tags were beautifully implemented :) Thank you!

Would it be possible to either not allow a snapp to be added without a path or have a user be told that a tag is missing?

P.S. Do you see any issues with me manually changing userid of a snapp to another user via the db? This way I can just add all snaps and then I can change the owner to someone else for them to manage and when a user departs, I can just send them over to whoever takes their place.

**Comment by urania-dev** [comment]
I'll check ;)

Btw should be possible to change user id i don't recall locking it on any way, need to check that the relationship keeps working after tho

**Comment by LeaveitT0uchless** [comment]
Nice thank you 😊 

Yeah I've been manually changing it and it doesn't seem to break any relationship but I'm not an expert so just wanted to asked to see if you can think of any issues I might face down the road by doing this.

**Comment by urania-dev** [comment]
yeah the worst that could happen is littering the db with unavailable relation and maybe the metrics are not perfect in that case, but that should be all :)

next version is contemplating the tag necessities in case of tags_as_prefix :)

**Comment by urania-dev** [comment]
fixed in 0.8.7.3 (building rn)
