### ISSUE TITLE
Unami and ALLOW_UNSECURE_HTTP

### ISSUE THREAD

**Issue by LeaveitT0uchless** [urania-dev/snapp#64]
Could it just be me? Unami settings not sticking and did env ALLOW_UNSECURE_HTTP get removed?

**Comment by urania-dev** [comment]
Mh weird. I'll check

**Comment by urania-dev** [comment]
Allow unsecure http it should be still available at the settings panel

while umami seems reporting correctly to my instance, does the docker have logs related?

**Comment by LeaveitT0uchless** [comment]
So you're able to set ALLOW_UNSECURE_HTTP: "true" and it loads with it on from startup?

Umani, I set the ID and website as variables but they don't come up on the settings page, maybe it's there but not showing?

I don't show any errors, I just see that my stmp and virustotal api gets enabled but that's it.

I'm on a m3 Mac so maybe just arm related?

**Comment by urania-dev** [comment]
no i mean that the cycle of picking up env starts only at the first instantiation of the app, after that you can change them from the ui and the database saved value have priority. this happens with all the settings available also in UI

**Comment by urania-dev** [comment]
let me know if it works as set on FE

**Comment by LeaveitT0uchless** [comment]
I fixed this changing 

From:
PUBLIC_UMAMI_WEBSITE_URL=
To:
PUBLIC_UMAMI_URL=

The README should be updated. 

P.S. on src/lib/server/db/database.ts the SMTP message shows: "SMPT Setup: configuration added to the database." there's a small typo.

I'd like to contribute but I'm new to github so I'm not sure how, sorry for adding more work
