### ISSUE TITLE
Not able to add any shortcodes when tags_as_prefix is on

### ISSUE THREAD

**Issue by LeaveitT0uchless** [urania-dev/snapp#68]
After the last update, even when I have tag selected, it won't let me as shortcodes, just continues to give the error:
This SNAPP has no prefix, please select one
![2024-10-20_15-29-54](https://github.com/user-attachments/assets/cadff92f-ffdd-4130-b464-5c98fa9e25fa)

This happens as user or root. on the logs I see:

TAGS_AS_PREFIX
TAGS_AS_PREFIX
TAGS_AS_PREFIX
TAGS_AS_PREFIX
TAGS_AS_PREFIX

**Comment by urania-dev** [comment]
Argh, i'll see into it

**Comment by LeaveitT0uchless** [comment]
wait, just ran yours vanilla and it works, so let me see what's different on my end.

The only thing different I can think of right now is I'm running mariadb on RDS so let me try to see what else is different.

**Comment by urania-dev** [comment]
no it was just me messing with the code actually

**Comment by urania-dev** [comment]
building fixed, let me know

**Comment by LeaveitT0uchless** [comment]
going, let you know in a bit

**Comment by LeaveitT0uchless** [comment]
It's good now :)

However, I noticed a small bug when there is no https in the error message is:

![image](https://github.com/user-attachments/assets/88f3aeb9-fbe7-4941-b930-0543dac43339)
 instead of the actual issue.
 
 Also, is Tags on by default now? so I can delete the env from my compose.

**Comment by urania-dev** [comment]
damnit. i always miss something. 🗡️ 

if you mean tags as prefix, no it is too much of a use case, tags as a whole, yeah they are 🤔 

btw, try api/qrcode/[...path]

**Comment by LeaveitT0uchless** [comment]
oh wait then no it's not working :( I just turned the flag on for tag as a prefix and it doesn't work, only when I don't enable it it works.

I saw your changes to qr :) I need to play with it!

**Comment by LeaveitT0uchless** [comment]
![image](https://github.com/user-attachments/assets/86f09ca3-d33e-438d-8dd9-c61fecabd2df)

It's selected but not working. I think I need to understand the difference between the 2, not I understand what one does vs the other even after reading the changelog file

**Comment by LeaveitT0uchless** [comment]
What I see on browser inspect:


{type: "failure", status: 400, data: "[{"message":1},"errors.snapps.no-prefix"]"}
data
: 
"[{\"message\":1},\"errors.snapps.no-prefix\"]"
status
: 
400
type
: 
"failure"

**Comment by urania-dev** [comment]
building 0.8.7.4.1, should fix that inconvinience.

**Comment by urania-dev** [comment]
yeah yeah, it was me all along, i found the arcane, the code was almost correct, but i repeatedly treated the tags with id instead of slug, hence generating caos across the database.
