### ISSUE TITLE
Creating snapps via API with  TAGS_AS_PREFIX: "true" failing

### ISSUE THREAD

**Issue by lit-carlos** [urania-dev/snapp#70]
Continue getting {"message":"This Snapps has no prefix selected, please include one."}

'{
    "shortcode": "geo",
    "original_url": "https://example.com",
    "disabled": false,
    "tags": ["test"],
    "userId": "u5s79579"
  }'

{"message":"This Snapps has no prefix selected, please include one."}%

**Comment by urania-dev** [comment]
look like i didn't included tags in snapp creation payload, fixing it

**Comment by lit-carlos** [comment]
Fixed now :)
