### ISSUE TITLE
API doesn't have same error handling as dashboard

### ISSUE THREAD

**Issue by lit-carlos** [urania-dev/snapp#71]
Through the API, adding a snapp test/test, goes through with no issues. On the dashboard, this is avoided but not taking the / on the shortcode field.

**Comment by urania-dev** [comment]
What? XD

**Comment by lit-carlos** [comment]
If you use this on the API: 

curl -X POST http://localhost:3000/api/snapps \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $API_TOKEN" \
  -d '{
    "shortcode": "test/geo",
    "original_url": "https://example.com",
    "notes": "GeoIP Test",
    "disabled": false,
    "tags": ["test"]
  }'

It will succeed, but the shortcode will have the / and therefore invalid. I guess the fix is just some validation on the API. On the Dashboard, you can't make this mistake because because it doesn't let you use a / on the shortcode field.

**Comment by urania-dev** [comment]
should be already fixed :)
