### ISSUE TITLE
Error in TOTP configuration prevents access to the root account.

### ISSUE THREAD

**Issue by cabaseira** [urania-dev/snapp#74]
When activating TOTP access I have not finished configuring it, since I use Vaultwarden as a password manager in my browser, and I cannot scan the QR code that is automatically generated from the same computer I am browsing on.
Since I have not been able to scan the QR, the TOTP codes have not been generated either.
But Snapp, instead of deactivating TOTP access until the entry of a valid temporary code is completed, has interpreted that the configuration was complete, and I can no longer enter my root account because the application always asks me for a temporary code that I have not configured.
It would be nice if **only** when the configuration process is finished with a correct temporary code, the MFA TOTP is considered active. It would also be nice if when the QR code is generated to scan from the password manager, the code is offered in numeric format (not only in QR format), so that it can be copied and pasted from the same computer.

**Comment by urania-dev** [comment]
Have to say that the first TOTP instantiated requires more attention, that's for sure, also it should be possible to use SSO like keycloak for a more robust authentication

**Comment by divadwong68** [comment]
The TOTP is a problem.  I got locked out twice and had to start over.  I've decided to not use it at this point.

**Comment by urania-dev** [comment]
I'll see what i can fix as soon as I have some spare time. Meanwhile of totp _is required_ you can attach a SSO like keycloak or Google oauth

So your data are secure :)

**Comment by cabaseira** [comment]
The app is great anyway. Congrats!!

**Comment by urania-dev** [comment]
building now, TOTP oauth setup now integrate a failsafe on first attempt, if everything is okay it sets up db, otherwise prompt a new qrcode.

also qrcode now has download button for text configuration of otpauth:/totp/domain:username etc etc. and for qrcode svg :)

**Comment by divadwong68** [comment]
Looks good now.  But I didn't realize MFA would be enabled for all users. At least I don't get locked out. :)

**Comment by urania-dev** [comment]
> Looks good now. But I didn't realize MFA would be enabled for all users. At least I don't get locked out. :)

thank you :D
