### ISSUE TITLE
Issues on link details screen

### ISSUE THREAD

**Issue by divadwong68** [urania-dev/snapp#75]
![Screen Shot 2024-12-28 at 11 13 37 PM](https://github.com/user-attachments/assets/11331a1c-b6e2-49d1-882c-1d1a98d5a7d1)

if you're in the detail screen and click on copy, the url is incorrect.  The Host/domain part shows up as undefined

The QR code also has this undefined issue.

I found this URL Shortener to be very well designed with a few bugs.  I've played with 3 or 4 and this one is the one I like the most and will use.

**Comment by urania-dev** [comment]
Thank for taking the time to document the issue and test the app!

I'll see to it in next vrs

**Comment by urania-dev** [comment]
building now fix for this and that button highlighting for no reason (edit snapp button on the bottom right of your screen)

**Comment by divadwong68** [comment]
That was fast.  Looks good now.
