### ISSUE TITLE
Signup allowed always

### ISSUE THREAD

**Issue by viriatusX** [urania-dev/snapp#8]
Hello,
I don't have the Docker MULTIUSER variable enabled, but I can still create multiple accounts. is it a bug?

**Comment by urania-dev** [comment]
Well. It should be false by default. I'll look into it. Can you try set ENABLE_MULTIUSER to false just to be sure and see if it works?

**Comment by viriatusX** [comment]
Nothing.. Even if you set the variable: ENABLE_MULTIUSER to false, Allows you to create new user accounts.

**Comment by urania-dev** [comment]
i think there is something wrong with your instance, are you using docker compose by any chance? 
what are the props set?

**Comment by viriatusX** [comment]
Yes, I use Docker-Compose on my Unraid:

services:
    snapp:
        environment:
            - ORIGIN=https://xxxxxxxx.com
            - PUBLIC_URL=https://xxxxxxxx.com
            - UMAMI_URL=https://umami.xxxxxx.com
            - UMAMI_ID=xxxxxxxxxxxxxxx
            - ENABLE_MULTIUSER=false
        ports:
            - 5023:3000
        image: uraniadev/snapp:latest

**Comment by urania-dev** [comment]
Nothing, it seems i'm unable to find the origin of your problem.

the app looks into that env, it seems your docker container doens't actually reads envs? doesn't seems possible.

also the code leave no doubt, in case of the env and of an already existing account it should stop signups. 

i'll let you know if i can get over it, but at this time i could not think of anything. sorry.

**Comment by viriatusX** [comment]
Solved with this:

```
 volumes:
            - /mnt/user/appdata/snapp/db.sqlite:/app/prisma/db.sqlite
```

Thanks :)

**Comment by urania-dev** [comment]
Ah! so it was db related and not env related. Happy to hear that it works for you know, just for future reference can I ask what was the config before? unset? in that case it should work anyway, but i'll check into it, like it couldn't find any user registered as it couldn't find the db? 

Thank you for your feedback, hope you enjoy snapp!
